# Generated by Django 5.2.6 on 2025-10-09 21:59

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('nombre_producto', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('accesorios', 'Accesorios'), ('arrastre', 'Arrastre'), ('bateria', 'Batería'), ('bujia', 'Bujía'), ('empaque', 'Empaque'), ('filtro', 'Filtro'), ('jebe', 'Jebe'), ('motor', 'Motor'), ('suspension', 'Suspensión'), ('transmision', 'Transmisión'), ('llantas', 'Llantas'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'El precio no puede ser negativo.')])),
                ('precio_mayoreo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'El precio no puede ser negativo.')])),
                ('oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, 'El precio de oferta no puede ser negativo.')])),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000, 'El stock no puede superar 1 millón.')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, unique=True)),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Ingrese un número de teléfono válido.')])),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo válido.')])),
                ('direccion', models.TextField()),
                ('ruc_documento', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z\\-]+$', 'Ingrese un documento válido (solo letras, números y guiones).')], verbose_name='RUC / Documento Legal')),
                ('tipo_proveedor', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', max_length=20)),
                ('categorias', multiselectfield.db.fields.MultiSelectField(choices=[('motor', 'Motor'), ('arrastre', 'Arrastre'), ('transmision', 'Transmisión'), ('empaque', 'Empaque'), ('bateria', 'Batería'), ('bujia', 'Bujía'), ('jebe', 'Jebe'), ('suspension', 'Suspensión'), ('llantas', 'Llantas'), ('accesorios', 'Accesorios'), ('filtro', 'Filtro'), ('otros', 'Otros')], default='otros', max_length=96)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('last_resend_time', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('postal', models.CharField(blank=True, max_length=20, null=True)),
                ('nota_adi', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='tienda.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.cart')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.proveedor'),
        ),
    ]
