# Generated by Django 5.2.7 on 2025-10-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_nombre_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
