# Generated by Django 5.2.7 on 2025-11-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='usuario',
        ),
    ]
