# Generated by Django 5.2.7 on 2026-07-04 09:33

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_rename_user_cart_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(location='media'), upload_to=''),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
